dist: trusty
sudo: required
language: clojure

cache:
  directories:
    - $HOME/.npm
    - $TRAVIS_BUILD_DIR/.cache
    - $TRAVIS_BUILD_DIR/node_modules

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y leiningen
  - nvm install --lts && nvm use --lts && npm install
  - sudo npm install -g lumo-cljs

install:
  - jdk_switcher use openjdk8

script: lein do check, eastwood, test, tach lumo, test-readme
